#全局 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
   #ip 显示
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    health-check-url-path: /health
    #ip-address: localhost

#zipkin 配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 111111

  zipkin:
    base-url: http://localhost:1158
  # spring boot admin 监控地址配置
  boot:
    admin:
      client:
        prefer-ip: true   # 解决windows下运行时无法识别主机名的问题
      url: http://localhost:8855   # 向服务端注册的地址
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false


#log 配置
logging:
  file: D:\Logs\com\config.log



#配置数据库公共配置
define:
  druid:
    username: admin
    password: 111111
  mysql:
    write:
      url: jdbc:mysql://192.168.1.139:3306/naju2_dev?useUnicode=true&characterEncoding=utf8
      username: naju2_master
      password: 111111
    read1:
      url: jdbc:mysql://192.168.1.139:3306/naju2_dev?useUnicode=true&characterEncoding=utf8
      username: naju2_slave
      password: 111111
  paging:
    defaultSize: 15      #默认分页大小
    defaultNum: 1
