eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

info:
  build:
    name: "@project.name@"
    description: "@project.description@"
    groupId: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"



spring:
  boot:
    admin:
      client:
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题
      url: http://localhost:8855 # 向服务端注册的地址
management:
  port: 64001
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false
info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

