eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
  instance:
    preferIpAddress: true


spring:
  boot:
    admin:
      #client:
       # prefer-ip: true   # 解决windows下运行时无法识别主机名的问题
      url: http://localhost:8855   # 向服务端注册的地址
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false


logging:
  file: D:\Logs\com\config.log

