#全局 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
   #ip 显示
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    health-check-url-path: /health
    #ip-address: localhost

#zipkin 配置
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
 #   password: 111111

  #redis:
   # database: 0   # Redis数据库索引（默认为0）
   # host: 127.0.0.1
   # password: admin
   # port: 6379
#################redis线程池设置#################
    #jedis:
     # pool:
      #  max-idle: 500  # 连接池中的最大空闲连接，默认值也是8
       # min-idle: 50   #连接池中的最小空闲连接，默认值也是0。
       # max-active: 2000
       # max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #timeout: 3000

 # zipkin:
  #  base-url: http://localhost:1158
  # spring boot admin 监控地址配置
 # boot:
  #  admin:
   #   client:
    #    prefer-ip: true   # 解决windows下运行时无法识别主机名的问题
    #  url: http://localhost:8855   # 向服务端注册的地址
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false



#配置数据库公共配置
define:
  druid:
    username: admin
    password: 111111
  mysql:
    write:
      url: jdbc:mysql://121.40.227.121:3306/yfApp?useUnicode=true&characterEncoding=UTF-8
      #url: jdbc:mysql://121.40.227.121:3306/jucaipen?useUnicode=true&characterEncoding=utf8
      #username: jucaipen
      username: master1
      password: 123456
      #password: jucaipen168
    read1:
      url: jdbc:mysql://121.40.227.121:3306/yfApp?useUnicode=true&characterEncoding=UTF-8
      #url: jdbc:mysql://121.40.227.121:3306/jucaipen?useUnicode=true&characterEncoding=utf8
      #username: jucaipen
      username: reader1
      password: 123456
      #password: jucaipen168
    read2:
      url: jdbc:mysql://121.40.227.121:3306/yfApp?useUnicode=true&characterEncoding=UTF-8
      #url: jdbc:mysql://121.40.227.121:3306/jucaipen?useUnicode=true&characterEncoding=utf8
      #username: jucaipen
      username: reader2
      password: 123456
      #password: jucaipen168
  paging:
    defaultSize: 15      #默认分页大小
    defaultNum: 1


logging:
  file: /app/logs/${spring.application.name}.log
