define:
  zuul:
    filter:
      RoutesFilter:
        enable: true
      BlacklistFilter:
        enable: true
      AccessLogFilter:
        enable: true
      ResponseLogFilter:
        enable: true
      ErrorFilter:
        enable: true

#log 配置
logging:
  file: D:\Logs\com\yf\gateway.log