define:
  zuul:
    filter:
      RoutesFilter:
        enable: true
      BlacklistFilter:
        enable: true
      AccessLogFilter:
        enable: true
      ResponseLogFilter:
        enable: true
      ErrorFilter:
        enable: true