define:
  zuul:
    filter:
      RoutesFilter:
        enable: true
      BlacklistFilter:
        enable: true
      AccessLogFilter:
        enable: true
      ResponseLogFilter:
        enable: true
      ErrorFilter:
        enable: true
  limit:
    access: 50


#log 配置
logging:
  file: D:\Logs\com\yf\gateway.log

spring:
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1
    password: admin
    port: 6379
#################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500  # 连接池中的最大空闲连接，默认值也是8
        min-idle: 50   #连接池中的最小空闲连接，默认值也是0。
        max-active: 2000
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 3000