define:
  push:
    jpush:
      app_key: 111111

  product: product-service:eggs-V001
  auther: user-service:pro
  #主从库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    write:
      driverClassName: com.mysql.jdbc.Driver
      url: ${define.mysql.write.url}
      username: ${define.mysql.write.username}
      password: ${define.mysql.write.password}
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000 # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true
    read1:
      driverClassName: com.mysql.jdbc.Driver
      url: ${define.mysql.read1.url}
      username: ${define.mysql.read1.username}
      password: ${define.mysql.read1.password}
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true
    read2:
      driverClassName: com.mysql.jdbc.Driver
      url: ${define.mysql.read2.url}
      username: ${define.mysql.read2.username}
      password: ${define.mysql.read2.password}
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true


#log 配置
logging:
  file: D:\Logs\com\yf\product-service.log



spring:
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1
    password: admin
    port: 6379
#################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500  # 连接池中的最大空闲连接，默认值也是8
        min-idle: 50   #连接池中的最小空闲连接，默认值也是0。
        max-active: 2000
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 3000
